ALTER TABLE dbo.DimCustomers ADD CONSTRAINT PK_DimCustomers PRIMARY KEY NONCLUSTERED (CustomerID) NOT ENFORCED;
ALTER TABLE dbo.DimEmployees ADD CONSTRAINT PK_DimEmployees PRIMARY KEY NONCLUSTERED (EmployeeID) NOT ENFORCED;
ALTER TABLE dbo.DimProducts ADD CONSTRAINT PK_DimProducts PRIMARY KEY NONCLUSTERED (ProductID) NOT ENFORCED;
ALTER TABLE dbo.FactSales ADD CONSTRAINT PK_FactSales PRIMARY KEY NONCLUSTERED (SalesID) NOT ENFORCED;